#!/bin/bash
# PUBLIC DOMAIN https://github.com/jakeogh/emerge-mint-file

argcount=2
usage="file [--nofollow]"
test "$#" -le "${argcount}" || { echo "$0 ${usage}" > /dev/stderr && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="

orig_file="${1}"
shift
nofollow="${1-off}"
shift
#echo "${nofollow}"
if [ "${nofollow}" == "--nofollow" ]
then
    file="${orig_file}"
else
    file=`readlink -f "${orig_file}"`
fi

test -e "${file}" || { echo "File ${file} not found" && exit 1 ; }

echo "looking up original copy of ${file}"
#echo "target:"
#echo "/usr/portage/x11-base/xorg-server/xorg-server-1.16.4.ebuild"

package=`equery -q b "${file}"`
echo "package: ${package}"
test -z "${package}" && { echo "equery -q b ${file} failed to return a package, might not be a portage installed file, exiting" ; exit 1 ; }

package_category=`echo "${package}" | cut -d '/' -f 1`
echo "package_category: ${package_category}"

package_without_version=`equery -q b -n "${file}"`
echo "package_without_version: ${package_without_version}"

package_name_with_version=`echo "${package}" | cut -d '/' -f 2`
echo "package_name_with_version: ${package_name_with_version}"

work_folder="/var/tmp/portage/${package_category}/${package_name_with_version}/work"
echo "work_folder: ${work_folder}"
image_folder="/var/tmp/portage/${package_category}/${package_name_with_version}/image"
echo "image_folder: ${image_folder}"

target_file="${image_folder}/${file}"
#echo "${target_file}"

if [ -e "${target_file}" ];
then
    echo "${target_file}"
else
    ebuild="/usr/portage/${package_without_version}/${package_name_with_version}.ebuild"
    echo "${ebuild}"

    ebuild "${ebuild}" clean
    echo "running ebuild ${ebuild} unpack"
    ebuild "${ebuild}" unpack

    echo "compiling to make sure the file exists, todo: att find to check for possible results in ${work_folder}"
    ebuild "${ebuild}" compile
    echo "running ebuild ${ebuild} install"
    ebuild "${ebuild}" install
    echo "${target_file}"
fi

